/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities;


import com.sadb.entities.tables.AcademicYear;
import com.sadb.entities.tables.Block;
import com.sadb.entities.tables.ClassRoom;
import com.sadb.entities.tables.Conference;
import com.sadb.entities.tables.Discipline;
import com.sadb.entities.tables.Dormitory;
import com.sadb.entities.tables.EventType;
import com.sadb.entities.tables.Events;
import com.sadb.entities.tables.Faculty;
import com.sadb.entities.tables.FacultyLecturer;
import com.sadb.entities.tables.FormEducation;
import com.sadb.entities.tables.Groups;
import com.sadb.entities.tables.Lecturer;
import com.sadb.entities.tables.Megafaculty;
import com.sadb.entities.tables.Occupation;
import com.sadb.entities.tables.OdevityWeek;
import com.sadb.entities.tables.ProgramTrack;
import com.sadb.entities.tables.Publications;
import com.sadb.entities.tables.ReaderSheet;
import com.sadb.entities.tables.Results;
import com.sadb.entities.tables.Room;
import com.sadb.entities.tables.ScientificProject;
import com.sadb.entities.tables.Speciality;
import com.sadb.entities.tables.Student;
import com.sadb.entities.tables.TimeTable;
import com.sadb.entities.tables.TypeEdition;
import com.sadb.entities.tables.TypePosition;
import com.sadb.entities.tables.TypePublication;
import com.sadb.entities.tables.VariantOccupation;
import com.sadb.entities.tables.WeekDay;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index XPK_ACADEMIC_YEAR = Indexes0.XPK_ACADEMIC_YEAR;
    public static final Index BLOCK_PK = Indexes0.BLOCK_PK;
    public static final Index XPK_CLASS_ROOM = Indexes0.XPK_CLASS_ROOM;
    public static final Index CONFERENCE_PKEY = Indexes0.CONFERENCE_PKEY;
    public static final Index XPK_DISCIPLINE = Indexes0.XPK_DISCIPLINE;
    public static final Index DORMITORY_PK = Indexes0.DORMITORY_PK;
    public static final Index EVENT_TYPE_PK = Indexes0.EVENT_TYPE_PK;
    public static final Index EVENTS_PK = Indexes0.EVENTS_PK;
    public static final Index XPK_FAC = Indexes0.XPK_FAC;
    public static final Index XPK_FAC_LECTUR = Indexes0.XPK_FAC_LECTUR;
    public static final Index FORM_EDUCATION_PK = Indexes0.FORM_EDUCATION_PK;
    public static final Index XPK_GROUP = Indexes0.XPK_GROUP;
    public static final Index XPK_LECTURER = Indexes0.XPK_LECTURER;
    public static final Index XPK_MFAC = Indexes0.XPK_MFAC;
    public static final Index XPK_OCCUPATION = Indexes0.XPK_OCCUPATION;
    public static final Index XPK_ODEVITY_WEEK = Indexes0.XPK_ODEVITY_WEEK;
    public static final Index XPK_PROGRAM_TRACK = Indexes0.XPK_PROGRAM_TRACK;
    public static final Index PUBLICATIONS_PKEY = Indexes0.PUBLICATIONS_PKEY;
    public static final Index READER_SHEET_PKEY = Indexes0.READER_SHEET_PKEY;
    public static final Index XPK_RESULTS = Indexes0.XPK_RESULTS;
    public static final Index ROOM_PK = Indexes0.ROOM_PK;
    public static final Index SCIENTIFIC_PROJECT_PKEY = Indexes0.SCIENTIFIC_PROJECT_PKEY;
    public static final Index XPK_PROGR_SPECIALITY = Indexes0.XPK_PROGR_SPECIALITY;
    public static final Index STUDENT_PKEY = Indexes0.STUDENT_PKEY;
    public static final Index XPK_TIME_TABLE = Indexes0.XPK_TIME_TABLE;
    public static final Index TYPE_EDITION_PKEY = Indexes0.TYPE_EDITION_PKEY;
    public static final Index TYPE_POSITION_PKEY = Indexes0.TYPE_POSITION_PKEY;
    public static final Index TYPE_PUBLICATION_PKEY = Indexes0.TYPE_PUBLICATION_PKEY;
    public static final Index XPK_ARIANT_OCC = Indexes0.XPK_ARIANT_OCC;
    public static final Index XPK_WEEK_DAY = Indexes0.XPK_WEEK_DAY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index XPK_ACADEMIC_YEAR = Internal.createIndex("xpk_academic_year", AcademicYear.ACADEMIC_YEAR, new OrderField[] { AcademicYear.ACADEMIC_YEAR.ACADEM_YEAR_ID }, true);
        public static Index BLOCK_PK = Internal.createIndex("block_pk", Block.BLOCK, new OrderField[] { Block.BLOCK.ID }, true);
        public static Index XPK_CLASS_ROOM = Internal.createIndex("xpk_class_room", ClassRoom.CLASS_ROOM, new OrderField[] { ClassRoom.CLASS_ROOM.CLASS_ID }, true);
        public static Index CONFERENCE_PKEY = Internal.createIndex("conference_pkey", Conference.CONFERENCE, new OrderField[] { Conference.CONFERENCE.ID }, true);
        public static Index XPK_DISCIPLINE = Internal.createIndex("xpk_discipline", Discipline.DISCIPLINE, new OrderField[] { Discipline.DISCIPLINE.DISCIPLINE_ID }, true);
        public static Index DORMITORY_PK = Internal.createIndex("dormitory_pk", Dormitory.DORMITORY, new OrderField[] { Dormitory.DORMITORY.ID }, true);
        public static Index EVENT_TYPE_PK = Internal.createIndex("event_type_pk", EventType.EVENT_TYPE, new OrderField[] { EventType.EVENT_TYPE.ID }, true);
        public static Index EVENTS_PK = Internal.createIndex("events_pk", Events.EVENTS, new OrderField[] { Events.EVENTS.ID }, true);
        public static Index XPK_FAC = Internal.createIndex("xpk_fac", Faculty.FACULTY, new OrderField[] { Faculty.FACULTY.FAC_ID }, true);
        public static Index XPK_FAC_LECTUR = Internal.createIndex("xpk_fac_lectur", FacultyLecturer.FACULTY_LECTURER, new OrderField[] { FacultyLecturer.FACULTY_LECTURER.FAC_LECT_ID }, true);
        public static Index FORM_EDUCATION_PK = Internal.createIndex("form_education_pk", FormEducation.FORM_EDUCATION, new OrderField[] { FormEducation.FORM_EDUCATION.ID }, true);
        public static Index XPK_GROUP = Internal.createIndex("xpk_group", Groups.GROUPS, new OrderField[] { Groups.GROUPS.GROUP_ID }, true);
        public static Index XPK_LECTURER = Internal.createIndex("xpk_lecturer", Lecturer.LECTURER, new OrderField[] { Lecturer.LECTURER.LEC_ID }, true);
        public static Index XPK_MFAC = Internal.createIndex("xpk_mfac", Megafaculty.MEGAFACULTY, new OrderField[] { Megafaculty.MEGAFACULTY.MEGAFAC_ID }, true);
        public static Index XPK_OCCUPATION = Internal.createIndex("xpk_occupation", Occupation.OCCUPATION, new OrderField[] { Occupation.OCCUPATION.OCCUPATION_ID }, true);
        public static Index XPK_ODEVITY_WEEK = Internal.createIndex("xpk_odevity_week", OdevityWeek.ODEVITY_WEEK, new OrderField[] { OdevityWeek.ODEVITY_WEEK.ODEVITY_ID }, true);
        public static Index XPK_PROGRAM_TRACK = Internal.createIndex("xpk_program_track", ProgramTrack.PROGRAM_TRACK, new OrderField[] { ProgramTrack.PROGRAM_TRACK.PROG_ID }, true);
        public static Index PUBLICATIONS_PKEY = Internal.createIndex("publications_pkey", Publications.PUBLICATIONS, new OrderField[] { Publications.PUBLICATIONS.ID }, true);
        public static Index READER_SHEET_PKEY = Internal.createIndex("reader_sheet_pkey", ReaderSheet.READER_SHEET, new OrderField[] { ReaderSheet.READER_SHEET.ID }, true);
        public static Index XPK_RESULTS = Internal.createIndex("xpk_results", Results.RESULTS, new OrderField[] { Results.RESULTS.RESULT_ID }, true);
        public static Index ROOM_PK = Internal.createIndex("room_pk", Room.ROOM, new OrderField[] { Room.ROOM.ID }, true);
        public static Index SCIENTIFIC_PROJECT_PKEY = Internal.createIndex("scientific_project_pkey", ScientificProject.SCIENTIFIC_PROJECT, new OrderField[] { ScientificProject.SCIENTIFIC_PROJECT.ID }, true);
        public static Index XPK_PROGR_SPECIALITY = Internal.createIndex("xpk_progr_speciality", Speciality.SPECIALITY, new OrderField[] { Speciality.SPECIALITY.SPEC_ID }, true);
        public static Index STUDENT_PKEY = Internal.createIndex("student_pkey", Student.STUDENT, new OrderField[] { Student.STUDENT.ID }, true);
        public static Index XPK_TIME_TABLE = Internal.createIndex("xpk_time_table", TimeTable.TIME_TABLE, new OrderField[] { TimeTable.TIME_TABLE.OCCUPATION_ID, TimeTable.TIME_TABLE.WEEK_DAY_ID, TimeTable.TIME_TABLE.ODEVITY_ID, TimeTable.TIME_TABLE.VARIANT_OCCUPATION_ID, TimeTable.TIME_TABLE.CLASS_ID, TimeTable.TIME_TABLE.GROUP_ID, TimeTable.TIME_TABLE.DISCIPLINE_ID }, true);
        public static Index TYPE_EDITION_PKEY = Internal.createIndex("type_edition_pkey", TypeEdition.TYPE_EDITION, new OrderField[] { TypeEdition.TYPE_EDITION.ID }, true);
        public static Index TYPE_POSITION_PKEY = Internal.createIndex("type_position_pkey", TypePosition.TYPE_POSITION, new OrderField[] { TypePosition.TYPE_POSITION.ID }, true);
        public static Index TYPE_PUBLICATION_PKEY = Internal.createIndex("type_publication_pkey", TypePublication.TYPE_PUBLICATION, new OrderField[] { TypePublication.TYPE_PUBLICATION.ID }, true);
        public static Index XPK_ARIANT_OCC = Internal.createIndex("xpk_ariant_occ", VariantOccupation.VARIANT_OCCUPATION, new OrderField[] { VariantOccupation.VARIANT_OCCUPATION.VARIANT_OCCUPATION_ID }, true);
        public static Index XPK_WEEK_DAY = Internal.createIndex("xpk_week_day", WeekDay.WEEK_DAY, new OrderField[] { WeekDay.WEEK_DAY.WEEK_DAY_ID }, true);
    }
}
