/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities;


import com.SADB.Entities.tables.AcademicYear;
import com.SADB.Entities.tables.Block;
import com.SADB.Entities.tables.ClassRoom;
import com.SADB.Entities.tables.Conference;
import com.SADB.Entities.tables.Discipline;
import com.SADB.Entities.tables.Dormitory;
import com.SADB.Entities.tables.EventType;
import com.SADB.Entities.tables.Events;
import com.SADB.Entities.tables.Faculty;
import com.SADB.Entities.tables.FacultyLecturer;
import com.SADB.Entities.tables.FormEducation;
import com.SADB.Entities.tables.Groups;
import com.SADB.Entities.tables.Lecturer;
import com.SADB.Entities.tables.ListParticipant;
import com.SADB.Entities.tables.ListParticipantProject;
import com.SADB.Entities.tables.Megafaculty;
import com.SADB.Entities.tables.Occupation;
import com.SADB.Entities.tables.OdevityWeek;
import com.SADB.Entities.tables.ProgramTrack;
import com.SADB.Entities.tables.Publications;
import com.SADB.Entities.tables.ReaderSheet;
import com.SADB.Entities.tables.Results;
import com.SADB.Entities.tables.Room;
import com.SADB.Entities.tables.ScientificProject;
import com.SADB.Entities.tables.Speciality;
import com.SADB.Entities.tables.Student;
import com.SADB.Entities.tables.TimeTable;
import com.SADB.Entities.tables.TypeEdition;
import com.SADB.Entities.tables.TypePosition;
import com.SADB.Entities.tables.TypePublication;
import com.SADB.Entities.tables.VariantOccupation;
import com.SADB.Entities.tables.WeekDay;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.academic_year</code>.
     */
    public static final AcademicYear ACADEMIC_YEAR = com.SADB.Entities.tables.AcademicYear.ACADEMIC_YEAR;

    /**
     * The table <code>public.block</code>.
     */
    public static final Block BLOCK = com.SADB.Entities.tables.Block.BLOCK;

    /**
     * The table <code>public.class_room</code>.
     */
    public static final ClassRoom CLASS_ROOM = com.SADB.Entities.tables.ClassRoom.CLASS_ROOM;

    /**
     * The table <code>public.conference</code>.
     */
    public static final Conference CONFERENCE = com.SADB.Entities.tables.Conference.CONFERENCE;

    /**
     * The table <code>public.discipline</code>.
     */
    public static final Discipline DISCIPLINE = com.SADB.Entities.tables.Discipline.DISCIPLINE;

    /**
     * The table <code>public.dormitory</code>.
     */
    public static final Dormitory DORMITORY = com.SADB.Entities.tables.Dormitory.DORMITORY;

    /**
     * The table <code>public.event_type</code>.
     */
    public static final EventType EVENT_TYPE = com.SADB.Entities.tables.EventType.EVENT_TYPE;

    /**
     * The table <code>public.events</code>.
     */
    public static final Events EVENTS = com.SADB.Entities.tables.Events.EVENTS;

    /**
     * The table <code>public.faculty</code>.
     */
    public static final Faculty FACULTY = com.SADB.Entities.tables.Faculty.FACULTY;

    /**
     * The table <code>public.faculty_lecturer</code>.
     */
    public static final FacultyLecturer FACULTY_LECTURER = com.SADB.Entities.tables.FacultyLecturer.FACULTY_LECTURER;

    /**
     * The table <code>public.form_education</code>.
     */
    public static final FormEducation FORM_EDUCATION = com.SADB.Entities.tables.FormEducation.FORM_EDUCATION;

    /**
     * The table <code>public.groups</code>.
     */
    public static final Groups GROUPS = com.SADB.Entities.tables.Groups.GROUPS;

    /**
     * The table <code>public.lecturer</code>.
     */
    public static final Lecturer LECTURER = com.SADB.Entities.tables.Lecturer.LECTURER;

    /**
     * The table <code>public.list_participant</code>.
     */
    public static final ListParticipant LIST_PARTICIPANT = com.SADB.Entities.tables.ListParticipant.LIST_PARTICIPANT;

    /**
     * The table <code>public.list_participant_project</code>.
     */
    public static final ListParticipantProject LIST_PARTICIPANT_PROJECT = com.SADB.Entities.tables.ListParticipantProject.LIST_PARTICIPANT_PROJECT;

    /**
     * The table <code>public.megafaculty</code>.
     */
    public static final Megafaculty MEGAFACULTY = com.SADB.Entities.tables.Megafaculty.MEGAFACULTY;

    /**
     * The table <code>public.occupation</code>.
     */
    public static final Occupation OCCUPATION = com.SADB.Entities.tables.Occupation.OCCUPATION;

    /**
     * The table <code>public.odevity_week</code>.
     */
    public static final OdevityWeek ODEVITY_WEEK = com.SADB.Entities.tables.OdevityWeek.ODEVITY_WEEK;

    /**
     * The table <code>public.program_track</code>.
     */
    public static final ProgramTrack PROGRAM_TRACK = com.SADB.Entities.tables.ProgramTrack.PROGRAM_TRACK;

    /**
     * The table <code>public.publications</code>.
     */
    public static final Publications PUBLICATIONS = com.SADB.Entities.tables.Publications.PUBLICATIONS;

    /**
     * The table <code>public.reader_sheet</code>.
     */
    public static final ReaderSheet READER_SHEET = com.SADB.Entities.tables.ReaderSheet.READER_SHEET;

    /**
     * The table <code>public.results</code>.
     */
    public static final Results RESULTS = com.SADB.Entities.tables.Results.RESULTS;

    /**
     * The table <code>public.room</code>.
     */
    public static final Room ROOM = com.SADB.Entities.tables.Room.ROOM;

    /**
     * The table <code>public.scientific_project</code>.
     */
    public static final ScientificProject SCIENTIFIC_PROJECT = com.SADB.Entities.tables.ScientificProject.SCIENTIFIC_PROJECT;

    /**
     * The table <code>public.speciality</code>.
     */
    public static final Speciality SPECIALITY = com.SADB.Entities.tables.Speciality.SPECIALITY;

    /**
     * The table <code>public.student</code>.
     */
    public static final Student STUDENT = com.SADB.Entities.tables.Student.STUDENT;

    /**
     * The table <code>public.time_table</code>.
     */
    public static final TimeTable TIME_TABLE = com.SADB.Entities.tables.TimeTable.TIME_TABLE;

    /**
     * The table <code>public.type_edition</code>.
     */
    public static final TypeEdition TYPE_EDITION = com.SADB.Entities.tables.TypeEdition.TYPE_EDITION;

    /**
     * The table <code>public.type_position</code>.
     */
    public static final TypePosition TYPE_POSITION = com.SADB.Entities.tables.TypePosition.TYPE_POSITION;

    /**
     * The table <code>public.type_publication</code>.
     */
    public static final TypePublication TYPE_PUBLICATION = com.SADB.Entities.tables.TypePublication.TYPE_PUBLICATION;

    /**
     * The table <code>public.variant_occupation</code>.
     */
    public static final VariantOccupation VARIANT_OCCUPATION = com.SADB.Entities.tables.VariantOccupation.VARIANT_OCCUPATION;

    /**
     * The table <code>public.week_day</code>.
     */
    public static final WeekDay WEEK_DAY = com.SADB.Entities.tables.WeekDay.WEEK_DAY;
}
