/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.ConferenceRecord;

import java.sql.Date;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Conference extends TableImpl<ConferenceRecord> {

    private static final long serialVersionUID = -449534228;

    /**
     * The reference instance of <code>public.conference</code>
     */
    public static final Conference CONFERENCE = new Conference();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<ConferenceRecord> getRecordType() {
        return ConferenceRecord.class;
    }

    /**
     * The column <code>public.conference.id</code>.
     */
    public final TableField<ConferenceRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('conference_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.conference.name</code>.
     */
    public final TableField<ConferenceRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.conference.venue</code>.
     */
    public final TableField<ConferenceRecord, String> VENUE = createField("venue", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.conference.date_conference</code>.
     */
    public final TableField<ConferenceRecord, Date> DATE_CONFERENCE = createField("date_conference", org.jooq.impl.SQLDataType.DATE.nullable(false), this, "");

    /**
     * The column <code>public.conference.data_update</code>.
     */
    public final TableField<ConferenceRecord, Timestamp> DATA_UPDATE = createField("data_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.conference.data_create</code>.
     */
    public final TableField<ConferenceRecord, Timestamp> DATA_CREATE = createField("data_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.conference</code> table reference
     */
    public Conference() {
        this(DSL.name("conference"), null);
    }

    /**
     * Create an aliased <code>public.conference</code> table reference
     */
    public Conference(String alias) {
        this(DSL.name(alias), CONFERENCE);
    }

    /**
     * Create an aliased <code>public.conference</code> table reference
     */
    public Conference(Name alias) {
        this(alias, CONFERENCE);
    }

    private Conference(Name alias, Table<ConferenceRecord> aliased) {
        this(alias, aliased, null);
    }

    private Conference(Name alias, Table<ConferenceRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Conference(Table<O> child, ForeignKey<O, ConferenceRecord> key) {
        super(child, key, CONFERENCE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CONFERENCE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<ConferenceRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CONFERENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<ConferenceRecord> getPrimaryKey() {
        return Keys.CONFERENCE_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<ConferenceRecord>> getKeys() {
        return Arrays.<UniqueKey<ConferenceRecord>>asList(Keys.CONFERENCE_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Conference as(String alias) {
        return new Conference(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Conference as(Name alias) {
        return new Conference(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Conference rename(String name) {
        return new Conference(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Conference rename(Name name) {
        return new Conference(name, null);
    }
}
