/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.DisciplineRecord;

import java.math.BigDecimal;
import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Discipline extends TableImpl<DisciplineRecord> {

    private static final long serialVersionUID = 42038737;

    /**
     * The reference instance of <code>public.discipline</code>
     */
    public static final Discipline DISCIPLINE = new Discipline();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DisciplineRecord> getRecordType() {
        return DisciplineRecord.class;
    }

    /**
     * The column <code>public.discipline.discipline_id</code>.
     */
    public final TableField<DisciplineRecord, Integer> DISCIPLINE_ID = createField("discipline_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.discipline.discipline_name</code>.
     */
    public final TableField<DisciplineRecord, String> DISCIPLINE_NAME = createField("discipline_name", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.discipline.lections_hours</code>.
     */
    public final TableField<DisciplineRecord, BigDecimal> LECTIONS_HOURS = createField("lections_hours", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.discipline.practicals_hours</code>.
     */
    public final TableField<DisciplineRecord, BigDecimal> PRACTICALS_HOURS = createField("practicals_hours", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.discipline.labs_houes</code>.
     */
    public final TableField<DisciplineRecord, BigDecimal> LABS_HOUES = createField("labs_houes", org.jooq.impl.SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>public.discipline.education_standart_type</code>.
     */
    public final TableField<DisciplineRecord, String> EDUCATION_STANDART_TYPE = createField("education_standart_type", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.discipline.creat_time</code>.
     */
    public final TableField<DisciplineRecord, Timestamp> CREAT_TIME = createField("creat_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.discipline.update_time</code>.
     */
    public final TableField<DisciplineRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.discipline</code> table reference
     */
    public Discipline() {
        this(DSL.name("discipline"), null);
    }

    /**
     * Create an aliased <code>public.discipline</code> table reference
     */
    public Discipline(String alias) {
        this(DSL.name(alias), DISCIPLINE);
    }

    /**
     * Create an aliased <code>public.discipline</code> table reference
     */
    public Discipline(Name alias) {
        this(alias, DISCIPLINE);
    }

    private Discipline(Name alias, Table<DisciplineRecord> aliased) {
        this(alias, aliased, null);
    }

    private Discipline(Name alias, Table<DisciplineRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Discipline(Table<O> child, ForeignKey<O, DisciplineRecord> key) {
        super(child, key, DISCIPLINE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.XPK_DISCIPLINE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DisciplineRecord> getPrimaryKey() {
        return Keys.XPK_DISCIPLINE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DisciplineRecord>> getKeys() {
        return Arrays.<UniqueKey<DisciplineRecord>>asList(Keys.XPK_DISCIPLINE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Discipline as(String alias) {
        return new Discipline(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Discipline as(Name alias) {
        return new Discipline(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Discipline rename(String name) {
        return new Discipline(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Discipline rename(Name name) {
        return new Discipline(name, null);
    }
}
