/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables;


import com.SADB.Entities.Indexes;
import com.SADB.Entities.Keys;
import com.SADB.Entities.Public;
import com.SADB.Entities.tables.records.EventTypeRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventType extends TableImpl<EventTypeRecord> {

    private static final long serialVersionUID = -1629407587;

    /**
     * The reference instance of <code>public.event_type</code>
     */
    public static final EventType EVENT_TYPE = new EventType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<EventTypeRecord> getRecordType() {
        return EventTypeRecord.class;
    }

    /**
     * The column <code>public.event_type.id</code>.
     */
    public final TableField<EventTypeRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('event_type_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.event_type.name</code>.
     */
    public final TableField<EventTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.event_type.date_update</code>.
     */
    public final TableField<EventTypeRecord, Timestamp> DATE_UPDATE = createField("date_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.event_type.date_create</code>.
     */
    public final TableField<EventTypeRecord, Timestamp> DATE_CREATE = createField("date_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.event_type</code> table reference
     */
    public EventType() {
        this(DSL.name("event_type"), null);
    }

    /**
     * Create an aliased <code>public.event_type</code> table reference
     */
    public EventType(String alias) {
        this(DSL.name(alias), EVENT_TYPE);
    }

    /**
     * Create an aliased <code>public.event_type</code> table reference
     */
    public EventType(Name alias) {
        this(alias, EVENT_TYPE);
    }

    private EventType(Name alias, Table<EventTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private EventType(Name alias, Table<EventTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> EventType(Table<O> child, ForeignKey<O, EventTypeRecord> key) {
        super(child, key, EVENT_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.EVENT_TYPE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<EventTypeRecord, Integer> getIdentity() {
        return Keys.IDENTITY_EVENT_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<EventTypeRecord> getPrimaryKey() {
        return Keys.EVENT_TYPE_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<EventTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<EventTypeRecord>>asList(Keys.EVENT_TYPE_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventType as(String alias) {
        return new EventType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventType as(Name alias) {
        return new EventType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public EventType rename(String name) {
        return new EventType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public EventType rename(Name name) {
        return new EventType(name, null);
    }
}
