/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.FormEducationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FormEducation extends TableImpl<FormEducationRecord> {

    private static final long serialVersionUID = 1355566241;

    /**
     * The reference instance of <code>public.form_education</code>
     */
    public static final FormEducation FORM_EDUCATION = new FormEducation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FormEducationRecord> getRecordType() {
        return FormEducationRecord.class;
    }

    /**
     * The column <code>public.form_education.id</code>.
     */
    public final TableField<FormEducationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('form_education_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.form_education.name</code>.
     */
    public final TableField<FormEducationRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.form_education.date_update</code>.
     */
    public final TableField<FormEducationRecord, Timestamp> DATE_UPDATE = createField("date_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.form_education.date_create</code>.
     */
    public final TableField<FormEducationRecord, Timestamp> DATE_CREATE = createField("date_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.form_education</code> table reference
     */
    public FormEducation() {
        this(DSL.name("form_education"), null);
    }

    /**
     * Create an aliased <code>public.form_education</code> table reference
     */
    public FormEducation(String alias) {
        this(DSL.name(alias), FORM_EDUCATION);
    }

    /**
     * Create an aliased <code>public.form_education</code> table reference
     */
    public FormEducation(Name alias) {
        this(alias, FORM_EDUCATION);
    }

    private FormEducation(Name alias, Table<FormEducationRecord> aliased) {
        this(alias, aliased, null);
    }

    private FormEducation(Name alias, Table<FormEducationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> FormEducation(Table<O> child, ForeignKey<O, FormEducationRecord> key) {
        super(child, key, FORM_EDUCATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FORM_EDUCATION_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<FormEducationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_FORM_EDUCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FormEducationRecord> getPrimaryKey() {
        return Keys.FORM_EDUCATION_PK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FormEducationRecord>> getKeys() {
        return Arrays.<UniqueKey<FormEducationRecord>>asList(Keys.FORM_EDUCATION_PK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormEducation as(String alias) {
        return new FormEducation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FormEducation as(Name alias) {
        return new FormEducation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FormEducation rename(String name) {
        return new FormEducation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FormEducation rename(Name name) {
        return new FormEducation(name, null);
    }
}
