/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.GroupsRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Groups extends TableImpl<GroupsRecord> {

    private static final long serialVersionUID = 1378586750;

    /**
     * The reference instance of <code>public.groups</code>
     */
    public static final Groups GROUPS = new Groups();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GroupsRecord> getRecordType() {
        return GroupsRecord.class;
    }

    /**
     * The column <code>public.groups.group_id</code>.
     */
    public final TableField<GroupsRecord, Integer> GROUP_ID = createField("group_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.groups.spec_id</code>.
     */
    public final TableField<GroupsRecord, Integer> SPEC_ID = createField("spec_id", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.groups.group_num</code>.
     */
    public final TableField<GroupsRecord, String> GROUP_NUM = createField("group_num", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.groups.course</code>.
     */
    public final TableField<GroupsRecord, Integer> COURSE = createField("course", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.groups.education_time_from</code>.
     */
    public final TableField<GroupsRecord, Timestamp> EDUCATION_TIME_FROM = createField("education_time_from", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.groups.education_time_to</code>.
     */
    public final TableField<GroupsRecord, Timestamp> EDUCATION_TIME_TO = createField("education_time_to", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.groups.academ_year_id</code>.
     */
    public final TableField<GroupsRecord, Integer> ACADEM_YEAR_ID = createField("academ_year_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.groups.creat_time</code>.
     */
    public final TableField<GroupsRecord, Timestamp> CREAT_TIME = createField("creat_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.groups.update_time</code>.
     */
    public final TableField<GroupsRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.groups</code> table reference
     */
    public Groups() {
        this(DSL.name("groups"), null);
    }

    /**
     * Create an aliased <code>public.groups</code> table reference
     */
    public Groups(String alias) {
        this(DSL.name(alias), GROUPS);
    }

    /**
     * Create an aliased <code>public.groups</code> table reference
     */
    public Groups(Name alias) {
        this(alias, GROUPS);
    }

    private Groups(Name alias, Table<GroupsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Groups(Name alias, Table<GroupsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Groups(Table<O> child, ForeignKey<O, GroupsRecord> key) {
        super(child, key, GROUPS);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.XPK_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GroupsRecord> getPrimaryKey() {
        return Keys.XPK_GROUP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GroupsRecord>> getKeys() {
        return Arrays.<UniqueKey<GroupsRecord>>asList(Keys.XPK_GROUP);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GroupsRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GroupsRecord, ?>>asList(Keys.GROUPS__R_6, Keys.GROUPS__R_29);
    }

    public Speciality speciality() {
        return new Speciality(this, Keys.GROUPS__R_6);
    }

    public AcademicYear academicYear() {
        return new AcademicYear(this, Keys.GROUPS__R_29);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Groups as(String alias) {
        return new Groups(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Groups as(Name alias) {
        return new Groups(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(String name) {
        return new Groups(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Groups rename(Name name) {
        return new Groups(name, null);
    }
}
