/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.OccupationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Occupation extends TableImpl<OccupationRecord> {

    private static final long serialVersionUID = -1734532107;

    /**
     * The reference instance of <code>public.occupation</code>
     */
    public static final Occupation OCCUPATION = new Occupation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OccupationRecord> getRecordType() {
        return OccupationRecord.class;
    }

    /**
     * The column <code>public.occupation.occupation_id</code>.
     */
    public final TableField<OccupationRecord, Integer> OCCUPATION_ID = createField("occupation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.occupation.occupaton_num</code>.
     */
    public final TableField<OccupationRecord, Integer> OCCUPATON_NUM = createField("occupaton_num", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.occupation.occupation_time_from</code>.
     */
    public final TableField<OccupationRecord, Timestamp> OCCUPATION_TIME_FROM = createField("occupation_time_from", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.occupation.occupation_time_to</code>.
     */
    public final TableField<OccupationRecord, Timestamp> OCCUPATION_TIME_TO = createField("occupation_time_to", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.occupation.creat_time</code>.
     */
    public final TableField<OccupationRecord, Timestamp> CREAT_TIME = createField("creat_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.occupation.update_time</code>.
     */
    public final TableField<OccupationRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.occupation</code> table reference
     */
    public Occupation() {
        this(DSL.name("occupation"), null);
    }

    /**
     * Create an aliased <code>public.occupation</code> table reference
     */
    public Occupation(String alias) {
        this(DSL.name(alias), OCCUPATION);
    }

    /**
     * Create an aliased <code>public.occupation</code> table reference
     */
    public Occupation(Name alias) {
        this(alias, OCCUPATION);
    }

    private Occupation(Name alias, Table<OccupationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Occupation(Name alias, Table<OccupationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> Occupation(Table<O> child, ForeignKey<O, OccupationRecord> key) {
        super(child, key, OCCUPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.XPK_OCCUPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OccupationRecord> getPrimaryKey() {
        return Keys.XPK_OCCUPATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OccupationRecord>> getKeys() {
        return Arrays.<UniqueKey<OccupationRecord>>asList(Keys.XPK_OCCUPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Occupation as(String alias) {
        return new Occupation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Occupation as(Name alias) {
        return new Occupation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Occupation rename(String name) {
        return new Occupation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Occupation rename(Name name) {
        return new Occupation(name, null);
    }
}
