/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.OdevityWeekRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdevityWeek extends TableImpl<OdevityWeekRecord> {

    private static final long serialVersionUID = -606107440;

    /**
     * The reference instance of <code>public.odevity_week</code>
     */
    public static final OdevityWeek ODEVITY_WEEK = new OdevityWeek();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OdevityWeekRecord> getRecordType() {
        return OdevityWeekRecord.class;
    }

    /**
     * The column <code>public.odevity_week.odevity_id</code>.
     */
    public final TableField<OdevityWeekRecord, Integer> ODEVITY_ID = createField("odevity_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.odevity_week.week</code>.
     */
    public final TableField<OdevityWeekRecord, String> WEEK = createField("week", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.odevity_week.creat_time</code>.
     */
    public final TableField<OdevityWeekRecord, Timestamp> CREAT_TIME = createField("creat_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.odevity_week.update_time</code>.
     */
    public final TableField<OdevityWeekRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.odevity_week</code> table reference
     */
    public OdevityWeek() {
        this(DSL.name("odevity_week"), null);
    }

    /**
     * Create an aliased <code>public.odevity_week</code> table reference
     */
    public OdevityWeek(String alias) {
        this(DSL.name(alias), ODEVITY_WEEK);
    }

    /**
     * Create an aliased <code>public.odevity_week</code> table reference
     */
    public OdevityWeek(Name alias) {
        this(alias, ODEVITY_WEEK);
    }

    private OdevityWeek(Name alias, Table<OdevityWeekRecord> aliased) {
        this(alias, aliased, null);
    }

    private OdevityWeek(Name alias, Table<OdevityWeekRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> OdevityWeek(Table<O> child, ForeignKey<O, OdevityWeekRecord> key) {
        super(child, key, ODEVITY_WEEK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.XPK_ODEVITY_WEEK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<OdevityWeekRecord> getPrimaryKey() {
        return Keys.XPK_ODEVITY_WEEK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<OdevityWeekRecord>> getKeys() {
        return Arrays.<UniqueKey<OdevityWeekRecord>>asList(Keys.XPK_ODEVITY_WEEK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeek as(String alias) {
        return new OdevityWeek(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeek as(Name alias) {
        return new OdevityWeek(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public OdevityWeek rename(String name) {
        return new OdevityWeek(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OdevityWeek rename(Name name) {
        return new OdevityWeek(name, null);
    }
}
