/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.TypePublicationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypePublication extends TableImpl<TypePublicationRecord> {

    private static final long serialVersionUID = 2003217563;

    /**
     * The reference instance of <code>public.type_publication</code>
     */
    public static final TypePublication TYPE_PUBLICATION = new TypePublication();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypePublicationRecord> getRecordType() {
        return TypePublicationRecord.class;
    }

    /**
     * The column <code>public.type_publication.id</code>.
     */
    public final TableField<TypePublicationRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('type_publication_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.type_publication.name</code>.
     */
    public final TableField<TypePublicationRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.type_publication.data_update</code>.
     */
    public final TableField<TypePublicationRecord, Timestamp> DATA_UPDATE = createField("data_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.type_publication.data_create</code>.
     */
    public final TableField<TypePublicationRecord, Timestamp> DATA_CREATE = createField("data_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.type_publication</code> table reference
     */
    public TypePublication() {
        this(DSL.name("type_publication"), null);
    }

    /**
     * Create an aliased <code>public.type_publication</code> table reference
     */
    public TypePublication(String alias) {
        this(DSL.name(alias), TYPE_PUBLICATION);
    }

    /**
     * Create an aliased <code>public.type_publication</code> table reference
     */
    public TypePublication(Name alias) {
        this(alias, TYPE_PUBLICATION);
    }

    private TypePublication(Name alias, Table<TypePublicationRecord> aliased) {
        this(alias, aliased, null);
    }

    private TypePublication(Name alias, Table<TypePublicationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TypePublication(Table<O> child, ForeignKey<O, TypePublicationRecord> key) {
        super(child, key, TYPE_PUBLICATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TYPE_PUBLICATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TypePublicationRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TYPE_PUBLICATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TypePublicationRecord> getPrimaryKey() {
        return Keys.TYPE_PUBLICATION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TypePublicationRecord>> getKeys() {
        return Arrays.<UniqueKey<TypePublicationRecord>>asList(Keys.TYPE_PUBLICATION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePublication as(String alias) {
        return new TypePublication(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypePublication as(Name alias) {
        return new TypePublication(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TypePublication rename(String name) {
        return new TypePublication(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TypePublication rename(Name name) {
        return new TypePublication(name, null);
    }
}
