/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables;


import com.SADB.Entities.Indexes;
import com.SADB.Entities.Keys;
import com.SADB.Entities.Public;
import com.SADB.Entities.tables.records.TypeEditionRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TypeEdition extends TableImpl<TypeEditionRecord> {

    private static final long serialVersionUID = -1633889557;

    /**
     * The reference instance of <code>public.type_edition</code>
     */
    public static final TypeEdition TYPE_EDITION = new TypeEdition();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TypeEditionRecord> getRecordType() {
        return TypeEditionRecord.class;
    }

    /**
     * The column <code>public.type_edition.id</code>.
     */
    public final TableField<TypeEditionRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.field("nextval('type_edition_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>public.type_edition.name</code>.
     */
    public final TableField<TypeEditionRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.type_edition.data_update</code>.
     */
    public final TableField<TypeEditionRecord, Timestamp> DATA_UPDATE = createField("data_update", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * The column <code>public.type_edition.data_create</code>.
     */
    public final TableField<TypeEditionRecord, Timestamp> DATA_CREATE = createField("data_create", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false), this, "");

    /**
     * Create a <code>public.type_edition</code> table reference
     */
    public TypeEdition() {
        this(DSL.name("type_edition"), null);
    }

    /**
     * Create an aliased <code>public.type_edition</code> table reference
     */
    public TypeEdition(String alias) {
        this(DSL.name(alias), TYPE_EDITION);
    }

    /**
     * Create an aliased <code>public.type_edition</code> table reference
     */
    public TypeEdition(Name alias) {
        this(alias, TYPE_EDITION);
    }

    private TypeEdition(Name alias, Table<TypeEditionRecord> aliased) {
        this(alias, aliased, null);
    }

    private TypeEdition(Name alias, Table<TypeEditionRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> TypeEdition(Table<O> child, ForeignKey<O, TypeEditionRecord> key) {
        super(child, key, TYPE_EDITION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.TYPE_EDITION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<TypeEditionRecord, Integer> getIdentity() {
        return Keys.IDENTITY_TYPE_EDITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<TypeEditionRecord> getPrimaryKey() {
        return Keys.TYPE_EDITION_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<TypeEditionRecord>> getKeys() {
        return Arrays.<UniqueKey<TypeEditionRecord>>asList(Keys.TYPE_EDITION_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeEdition as(String alias) {
        return new TypeEdition(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TypeEdition as(Name alias) {
        return new TypeEdition(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeEdition rename(String name) {
        return new TypeEdition(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TypeEdition rename(Name name) {
        return new TypeEdition(name, null);
    }
}
