/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables;


import com.sadb.entities.Indexes;
import com.sadb.entities.Keys;
import com.sadb.entities.Public;
import com.sadb.entities.tables.records.VariantOccupationRecord;

import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class VariantOccupation extends TableImpl<VariantOccupationRecord> {

    private static final long serialVersionUID = -1406948605;

    /**
     * The reference instance of <code>public.variant_occupation</code>
     */
    public static final VariantOccupation VARIANT_OCCUPATION = new VariantOccupation();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<VariantOccupationRecord> getRecordType() {
        return VariantOccupationRecord.class;
    }

    /**
     * The column <code>public.variant_occupation.variant_occupation_id</code>.
     */
    public final TableField<VariantOccupationRecord, Integer> VARIANT_OCCUPATION_ID = createField("variant_occupation_id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.variant_occupation.var_occ_type</code>.
     */
    public final TableField<VariantOccupationRecord, String> VAR_OCC_TYPE = createField("var_occ_type", org.jooq.impl.SQLDataType.VARCHAR(20), this, "");

    /**
     * The column <code>public.variant_occupation.creat_time</code>.
     */
    public final TableField<VariantOccupationRecord, Timestamp> CREAT_TIME = createField("creat_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>public.variant_occupation.update_time</code>.
     */
    public final TableField<VariantOccupationRecord, Timestamp> UPDATE_TIME = createField("update_time", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>public.variant_occupation</code> table reference
     */
    public VariantOccupation() {
        this(DSL.name("variant_occupation"), null);
    }

    /**
     * Create an aliased <code>public.variant_occupation</code> table reference
     */
    public VariantOccupation(String alias) {
        this(DSL.name(alias), VARIANT_OCCUPATION);
    }

    /**
     * Create an aliased <code>public.variant_occupation</code> table reference
     */
    public VariantOccupation(Name alias) {
        this(alias, VARIANT_OCCUPATION);
    }

    private VariantOccupation(Name alias, Table<VariantOccupationRecord> aliased) {
        this(alias, aliased, null);
    }

    private VariantOccupation(Name alias, Table<VariantOccupationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, DSL.comment(""));
    }

    public <O extends Record> VariantOccupation(Table<O> child, ForeignKey<O, VariantOccupationRecord> key) {
        super(child, key, VARIANT_OCCUPATION);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.XPK_ARIANT_OCC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<VariantOccupationRecord> getPrimaryKey() {
        return Keys.XPK_ARIANT_OCC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<VariantOccupationRecord>> getKeys() {
        return Arrays.<UniqueKey<VariantOccupationRecord>>asList(Keys.XPK_ARIANT_OCC);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VariantOccupation as(String alias) {
        return new VariantOccupation(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public VariantOccupation as(Name alias) {
        return new VariantOccupation(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public VariantOccupation rename(String name) {
        return new VariantOccupation(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public VariantOccupation rename(Name name) {
        return new VariantOccupation(name, null);
    }
}
