/*
 * This file is generated by jOOQ.
 */
package com.sadb.examples.entites;


import com.sadb.examples.entites.tables.Car;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.car</code>.
     */
    public static final Car CAR = com.sadb.examples.entites.tables.Car.CAR;
}
