/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables.records;


import com.sadb.entities.tables.Block;

import java.sql.Date;
import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BlockRecord extends UpdatableRecordImpl<BlockRecord> implements Record6<Integer, Integer, Date, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1315627231;

    /**
     * Setter for <code>public.block.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.block.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.block.floor</code>.
     */
    public void setFloor(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.block.floor</code>.
     */
    public Integer getFloor() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.block.date_disinsection</code>.
     */
    public void setDateDisinsection(Date value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.block.date_disinsection</code>.
     */
    public Date getDateDisinsection() {
        return (Date) get(2);
    }

    /**
     * Setter for <code>public.block.dorm_id</code>.
     */
    public void setDormId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.block.dorm_id</code>.
     */
    public Integer getDormId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.block.date_update</code>.
     */
    public void setDateUpdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.block.date_update</code>.
     */
    public Timestamp getDateUpdate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.block.date_create</code>.
     */
    public void setDateCreate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.block.date_create</code>.
     */
    public Timestamp getDateCreate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Date, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Date, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Block.BLOCK.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Block.BLOCK.FLOOR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field3() {
        return Block.BLOCK.DATE_DISINSECTION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Block.BLOCK.DORM_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Block.BLOCK.DATE_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Block.BLOCK.DATE_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFloor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component3() {
        return getDateDisinsection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getDormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFloor();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value3() {
        return getDateDisinsection();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getDormId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord value2(Integer value) {
        setFloor(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord value3(Date value) {
        setDateDisinsection(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord value4(Integer value) {
        setDormId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord value5(Timestamp value) {
        setDateUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord value6(Timestamp value) {
        setDateCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BlockRecord values(Integer value1, Integer value2, Date value3, Integer value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BlockRecord
     */
    public BlockRecord() {
        super(Block.BLOCK);
    }

    /**
     * Create a detached, initialised BlockRecord
     */
    public BlockRecord(Integer id, Integer floor, Date dateDisinsection, Integer dormId, Timestamp dateUpdate, Timestamp dateCreate) {
        super(Block.BLOCK);

        set(0, id);
        set(1, floor);
        set(2, dateDisinsection);
        set(3, dormId);
        set(4, dateUpdate);
        set(5, dateCreate);
    }
}
