/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables.records;


import com.sadb.entities.tables.Events;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EventsRecord extends UpdatableRecordImpl<EventsRecord> implements Record6<Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -794847056;

    /**
     * Setter for <code>public.events.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.events.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.events.student_id</code>.
     */
    public void setStudentId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.events.student_id</code>.
     */
    public Integer getStudentId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.events.event_type_id</code>.
     */
    public void setEventTypeId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.events.event_type_id</code>.
     */
    public Integer getEventTypeId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.events.datetime</code>.
     */
    public void setDatetime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.events.datetime</code>.
     */
    public Timestamp getDatetime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.events.date_update</code>.
     */
    public void setDateUpdate(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.events.date_update</code>.
     */
    public Timestamp getDateUpdate() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.events.date_create</code>.
     */
    public void setDateCreate(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.events.date_create</code>.
     */
    public Timestamp getDateCreate() {
        return (Timestamp) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<Integer, Integer, Integer, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Events.EVENTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Events.EVENTS.STUDENT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Events.EVENTS.EVENT_TYPE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Events.EVENTS.DATETIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Events.EVENTS.DATE_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Events.EVENTS.DATE_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getEventTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getStudentId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getEventTypeId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDatetime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDateUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value2(Integer value) {
        setStudentId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value3(Integer value) {
        setEventTypeId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value4(Timestamp value) {
        setDatetime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value5(Timestamp value) {
        setDateUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord value6(Timestamp value) {
        setDateCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public EventsRecord values(Integer value1, Integer value2, Integer value3, Timestamp value4, Timestamp value5, Timestamp value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached EventsRecord
     */
    public EventsRecord() {
        super(Events.EVENTS);
    }

    /**
     * Create a detached, initialised EventsRecord
     */
    public EventsRecord(Integer id, Integer studentId, Integer eventTypeId, Timestamp datetime, Timestamp dateUpdate, Timestamp dateCreate) {
        super(Events.EVENTS);

        set(0, id);
        set(1, studentId);
        set(2, eventTypeId);
        set(3, datetime);
        set(4, dateUpdate);
        set(5, dateCreate);
    }
}
