/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables.records;


import com.SADB.Entities.tables.Faculty;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FacultyRecord extends UpdatableRecordImpl<FacultyRecord> implements Record5<Integer, String, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1825976249;

    /**
     * Setter for <code>public.faculty.fac_id</code>.
     */
    public void setFacId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.faculty.fac_id</code>.
     */
    public Integer getFacId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.faculty.fac_name</code>.
     */
    public void setFacName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.faculty.fac_name</code>.
     */
    public String getFacName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.faculty.megafac_id</code>.
     */
    public void setMegafacId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.faculty.megafac_id</code>.
     */
    public Integer getMegafacId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.faculty.creat_time</code>.
     */
    public void setCreatTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.faculty.creat_time</code>.
     */
    public Timestamp getCreatTime() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>public.faculty.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.faculty.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<Integer, String, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Faculty.FACULTY.FAC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Faculty.FACULTY.FAC_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Faculty.FACULTY.MEGAFAC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Faculty.FACULTY.CREAT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Faculty.FACULTY.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getFacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFacName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getMegafacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getFacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFacName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getMegafacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacultyRecord value1(Integer value) {
        setFacId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacultyRecord value2(String value) {
        setFacName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacultyRecord value3(Integer value) {
        setMegafacId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacultyRecord value4(Timestamp value) {
        setCreatTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacultyRecord value5(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FacultyRecord values(Integer value1, String value2, Integer value3, Timestamp value4, Timestamp value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FacultyRecord
     */
    public FacultyRecord() {
        super(Faculty.FACULTY);
    }

    /**
     * Create a detached, initialised FacultyRecord
     */
    public FacultyRecord(Integer facId, String facName, Integer megafacId, Timestamp creatTime, Timestamp updateTime) {
        super(Faculty.FACULTY);

        set(0, facId);
        set(1, facName);
        set(2, megafacId);
        set(3, creatTime);
        set(4, updateTime);
    }
}
