/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables.records;


import com.SADB.Entities.tables.Groups;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GroupsRecord extends UpdatableRecordImpl<GroupsRecord> implements Record9<Integer, Integer, String, Integer, Timestamp, Timestamp, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -2136770243;

    /**
     * Setter for <code>public.groups.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.groups.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.groups.spec_id</code>.
     */
    public void setSpecId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.groups.spec_id</code>.
     */
    public Integer getSpecId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.groups.group_num</code>.
     */
    public void setGroupNum(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.groups.group_num</code>.
     */
    public String getGroupNum() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.groups.course</code>.
     */
    public void setCourse(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.groups.course</code>.
     */
    public Integer getCourse() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.groups.education_time_from</code>.
     */
    public void setEducationTimeFrom(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.groups.education_time_from</code>.
     */
    public Timestamp getEducationTimeFrom() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>public.groups.education_time_to</code>.
     */
    public void setEducationTimeTo(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.groups.education_time_to</code>.
     */
    public Timestamp getEducationTimeTo() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.groups.academ_year_id</code>.
     */
    public void setAcademYearId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.groups.academ_year_id</code>.
     */
    public Integer getAcademYearId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.groups.creat_time</code>.
     */
    public void setCreatTime(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.groups.creat_time</code>.
     */
    public Timestamp getCreatTime() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>public.groups.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.groups.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, Integer, Timestamp, Timestamp, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, Integer, String, Integer, Timestamp, Timestamp, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Groups.GROUPS.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Groups.GROUPS.SPEC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Groups.GROUPS.GROUP_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Groups.GROUPS.COURSE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Groups.GROUPS.EDUCATION_TIME_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Groups.GROUPS.EDUCATION_TIME_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Groups.GROUPS.ACADEM_YEAR_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Groups.GROUPS.CREAT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Groups.GROUPS.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getSpecId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGroupNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getCourse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getEducationTimeFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getEducationTimeTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getAcademYearId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getSpecId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGroupNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getCourse();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getEducationTimeFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getEducationTimeTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getAcademYearId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value1(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value2(Integer value) {
        setSpecId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value3(String value) {
        setGroupNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value4(Integer value) {
        setCourse(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value5(Timestamp value) {
        setEducationTimeFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value6(Timestamp value) {
        setEducationTimeTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value7(Integer value) {
        setAcademYearId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value8(Timestamp value) {
        setCreatTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord value9(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GroupsRecord values(Integer value1, Integer value2, String value3, Integer value4, Timestamp value5, Timestamp value6, Integer value7, Timestamp value8, Timestamp value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GroupsRecord
     */
    public GroupsRecord() {
        super(Groups.GROUPS);
    }

    /**
     * Create a detached, initialised GroupsRecord
     */
    public GroupsRecord(Integer groupId, Integer specId, String groupNum, Integer course, Timestamp educationTimeFrom, Timestamp educationTimeTo, Integer academYearId, Timestamp creatTime, Timestamp updateTime) {
        super(Groups.GROUPS);

        set(0, groupId);
        set(1, specId);
        set(2, groupNum);
        set(3, course);
        set(4, educationTimeFrom);
        set(5, educationTimeTo);
        set(6, academYearId);
        set(7, creatTime);
        set(8, updateTime);
    }
}
