/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables.records;


import com.sadb.entities.tables.ListParticipantProject;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ListParticipantProjectRecord extends TableRecordImpl<ListParticipantProjectRecord> implements Record4<Integer, Integer, Timestamp, Timestamp> {

    private static final long serialVersionUID = -692089866;

    /**
     * Setter for <code>public.list_participant_project.participant_id</code>.
     */
    public void setParticipantId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.list_participant_project.participant_id</code>.
     */
    public Integer getParticipantId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.list_participant_project.project_id</code>.
     */
    public void setProjectId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.list_participant_project.project_id</code>.
     */
    public Integer getProjectId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.list_participant_project.data_update</code>.
     */
    public void setDataUpdate(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.list_participant_project.data_update</code>.
     */
    public Timestamp getDataUpdate() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.list_participant_project.data_create</code>.
     */
    public void setDataCreate(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.list_participant_project.data_create</code>.
     */
    public Timestamp getDataCreate() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, Integer, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ListParticipantProject.LIST_PARTICIPANT_PROJECT.PARTICIPANT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ListParticipantProject.LIST_PARTICIPANT_PROJECT.PROJECT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return ListParticipantProject.LIST_PARTICIPANT_PROJECT.DATA_UPDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return ListParticipantProject.LIST_PARTICIPANT_PROJECT.DATA_CREATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getParticipantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getDataUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getDataCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getParticipantId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getProjectId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getDataUpdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getDataCreate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ListParticipantProjectRecord value1(Integer value) {
        setParticipantId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ListParticipantProjectRecord value2(Integer value) {
        setProjectId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ListParticipantProjectRecord value3(Timestamp value) {
        setDataUpdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ListParticipantProjectRecord value4(Timestamp value) {
        setDataCreate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ListParticipantProjectRecord values(Integer value1, Integer value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ListParticipantProjectRecord
     */
    public ListParticipantProjectRecord() {
        super(ListParticipantProject.LIST_PARTICIPANT_PROJECT);
    }

    /**
     * Create a detached, initialised ListParticipantProjectRecord
     */
    public ListParticipantProjectRecord(Integer participantId, Integer projectId, Timestamp dataUpdate, Timestamp dataCreate) {
        super(ListParticipantProject.LIST_PARTICIPANT_PROJECT);

        set(0, participantId);
        set(1, projectId);
        set(2, dataUpdate);
        set(3, dataCreate);
    }
}
