/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables.records;


import com.SADB.Entities.tables.Megafaculty;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MegafacultyRecord extends UpdatableRecordImpl<MegafacultyRecord> implements Record4<Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = -984301603;

    /**
     * Setter for <code>public.megafaculty.megafac_id</code>.
     */
    public void setMegafacId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.megafaculty.megafac_id</code>.
     */
    public Integer getMegafacId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.megafaculty.mfaculty_name</code>.
     */
    public void setMfacultyName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.megafaculty.mfaculty_name</code>.
     */
    public String getMfacultyName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.megafaculty.creat_time</code>.
     */
    public void setCreatTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.megafaculty.creat_time</code>.
     */
    public Timestamp getCreatTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.megafaculty.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.megafaculty.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Megafaculty.MEGAFACULTY.MEGAFAC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Megafaculty.MEGAFACULTY.MFACULTY_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Megafaculty.MEGAFACULTY.CREAT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Megafaculty.MEGAFACULTY.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getMegafacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getMfacultyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getMegafacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getMfacultyName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegafacultyRecord value1(Integer value) {
        setMegafacId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegafacultyRecord value2(String value) {
        setMfacultyName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegafacultyRecord value3(Timestamp value) {
        setCreatTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegafacultyRecord value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MegafacultyRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MegafacultyRecord
     */
    public MegafacultyRecord() {
        super(Megafaculty.MEGAFACULTY);
    }

    /**
     * Create a detached, initialised MegafacultyRecord
     */
    public MegafacultyRecord(Integer megafacId, String mfacultyName, Timestamp creatTime, Timestamp updateTime) {
        super(Megafaculty.MEGAFACULTY);

        set(0, megafacId);
        set(1, mfacultyName);
        set(2, creatTime);
        set(3, updateTime);
    }
}
