/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables.records;


import com.SADB.Entities.tables.OdevityWeek;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OdevityWeekRecord extends UpdatableRecordImpl<OdevityWeekRecord> implements Record4<Integer, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1334647688;

    /**
     * Setter for <code>public.odevity_week.odevity_id</code>.
     */
    public void setOdevityId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.odevity_week.odevity_id</code>.
     */
    public Integer getOdevityId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.odevity_week.week</code>.
     */
    public void setWeek(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.odevity_week.week</code>.
     */
    public String getWeek() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.odevity_week.creat_time</code>.
     */
    public void setCreatTime(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.odevity_week.creat_time</code>.
     */
    public Timestamp getCreatTime() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>public.odevity_week.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.odevity_week.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Timestamp> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, Timestamp, Timestamp> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return OdevityWeek.ODEVITY_WEEK.ODEVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return OdevityWeek.ODEVITY_WEEK.WEEK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return OdevityWeek.ODEVITY_WEEK.CREAT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return OdevityWeek.ODEVITY_WEEK.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getOdevityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getWeek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component3() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getOdevityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getWeek();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeekRecord value1(Integer value) {
        setOdevityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeekRecord value2(String value) {
        setWeek(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeekRecord value3(Timestamp value) {
        setCreatTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeekRecord value4(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public OdevityWeekRecord values(Integer value1, String value2, Timestamp value3, Timestamp value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OdevityWeekRecord
     */
    public OdevityWeekRecord() {
        super(OdevityWeek.ODEVITY_WEEK);
    }

    /**
     * Create a detached, initialised OdevityWeekRecord
     */
    public OdevityWeekRecord(Integer odevityId, String week, Timestamp creatTime, Timestamp updateTime) {
        super(OdevityWeek.ODEVITY_WEEK);

        set(0, odevityId);
        set(1, week);
        set(2, creatTime);
        set(3, updateTime);
    }
}
