/*
 * This file is generated by jOOQ.
 */
package com.SADB.Entities.tables.records;


import com.SADB.Entities.tables.ProgramTrack;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProgramTrackRecord extends UpdatableRecordImpl<ProgramTrackRecord> implements Record7<Integer, Integer, String, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1133202308;

    /**
     * Setter for <code>public.program_track.prog_id</code>.
     */
    public void setProgId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.program_track.prog_id</code>.
     */
    public Integer getProgId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.program_track.fac_id</code>.
     */
    public void setFacId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.program_track.fac_id</code>.
     */
    public Integer getFacId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.program_track.progm_name</code>.
     */
    public void setProgmName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.program_track.progm_name</code>.
     */
    public String getProgmName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.program_track.program_track_num</code>.
     */
    public void setProgramTrackNum(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.program_track.program_track_num</code>.
     */
    public String getProgramTrackNum() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.program_track.progm_type</code>.
     */
    public void setProgmType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.program_track.progm_type</code>.
     */
    public String getProgmType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.program_track.creat_time</code>.
     */
    public void setCreatTime(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.program_track.creat_time</code>.
     */
    public Timestamp getCreatTime() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>public.program_track.update_time</code>.
     */
    public void setUpdateTime(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.program_track.update_time</code>.
     */
    public Timestamp getUpdateTime() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, String, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return ProgramTrack.PROGRAM_TRACK.PROG_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return ProgramTrack.PROGRAM_TRACK.FAC_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return ProgramTrack.PROGRAM_TRACK.PROGM_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return ProgramTrack.PROGRAM_TRACK.PROGRAM_TRACK_NUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return ProgramTrack.PROGRAM_TRACK.PROGM_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return ProgramTrack.PROGRAM_TRACK.CREAT_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return ProgramTrack.PROGRAM_TRACK.UPDATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getProgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getFacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getProgmName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProgramTrackNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getProgmType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProgId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getFacId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getProgmName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProgramTrackNum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getProgmType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getCreatTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getUpdateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value1(Integer value) {
        setProgId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value2(Integer value) {
        setFacId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value3(String value) {
        setProgmName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value4(String value) {
        setProgramTrackNum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value5(String value) {
        setProgmType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value6(Timestamp value) {
        setCreatTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord value7(Timestamp value) {
        setUpdateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProgramTrackRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProgramTrackRecord
     */
    public ProgramTrackRecord() {
        super(ProgramTrack.PROGRAM_TRACK);
    }

    /**
     * Create a detached, initialised ProgramTrackRecord
     */
    public ProgramTrackRecord(Integer progId, Integer facId, String progmName, String programTrackNum, String progmType, Timestamp creatTime, Timestamp updateTime) {
        super(ProgramTrack.PROGRAM_TRACK);

        set(0, progId);
        set(1, facId);
        set(2, progmName);
        set(3, programTrackNum);
        set(4, progmType);
        set(5, creatTime);
        set(6, updateTime);
    }
}
