/*
 * This file is generated by jOOQ.
 */
package com.sadb.entities.tables.records;


import com.sadb.entities.tables.TimeTable;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.9"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TimeTableRecord extends UpdatableRecordImpl<TimeTableRecord> implements Record7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> {

    private static final long serialVersionUID = 453638004;

    /**
     * Setter for <code>public.time_table.week_day_id</code>.
     */
    public void setWeekDayId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.time_table.week_day_id</code>.
     */
    public Integer getWeekDayId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.time_table.occupation_id</code>.
     */
    public void setOccupationId(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.time_table.occupation_id</code>.
     */
    public Integer getOccupationId() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>public.time_table.odevity_id</code>.
     */
    public void setOdevityId(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.time_table.odevity_id</code>.
     */
    public Integer getOdevityId() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>public.time_table.variant_occupation_id</code>.
     */
    public void setVariantOccupationId(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.time_table.variant_occupation_id</code>.
     */
    public Integer getVariantOccupationId() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.time_table.class_id</code>.
     */
    public void setClassId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.time_table.class_id</code>.
     */
    public Integer getClassId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.time_table.group_id</code>.
     */
    public void setGroupId(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.time_table.group_id</code>.
     */
    public Integer getGroupId() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.time_table.discipline_id</code>.
     */
    public void setDisciplineId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.time_table.discipline_id</code>.
     */
    public Integer getDisciplineId() {
        return (Integer) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> key() {
        return (Record7) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Integer, Integer, Integer, Integer> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return TimeTable.TIME_TABLE.WEEK_DAY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return TimeTable.TIME_TABLE.OCCUPATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return TimeTable.TIME_TABLE.ODEVITY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return TimeTable.TIME_TABLE.VARIANT_OCCUPATION_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field5() {
        return TimeTable.TIME_TABLE.CLASS_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return TimeTable.TIME_TABLE.GROUP_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return TimeTable.TIME_TABLE.DISCIPLINE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getWeekDayId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getOccupationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getOdevityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getVariantOccupationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component5() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getDisciplineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getWeekDayId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getOccupationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getOdevityId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getVariantOccupationId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value5() {
        return getClassId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getGroupId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getDisciplineId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value1(Integer value) {
        setWeekDayId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value2(Integer value) {
        setOccupationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value3(Integer value) {
        setOdevityId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value4(Integer value) {
        setVariantOccupationId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value5(Integer value) {
        setClassId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value6(Integer value) {
        setGroupId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord value7(Integer value) {
        setDisciplineId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TimeTableRecord values(Integer value1, Integer value2, Integer value3, Integer value4, Integer value5, Integer value6, Integer value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TimeTableRecord
     */
    public TimeTableRecord() {
        super(TimeTable.TIME_TABLE);
    }

    /**
     * Create a detached, initialised TimeTableRecord
     */
    public TimeTableRecord(Integer weekDayId, Integer occupationId, Integer odevityId, Integer variantOccupationId, Integer classId, Integer groupId, Integer disciplineId) {
        super(TimeTable.TIME_TABLE);

        set(0, weekDayId);
        set(1, occupationId);
        set(2, odevityId);
        set(3, variantOccupationId);
        set(4, classId);
        set(5, groupId);
        set(6, disciplineId);
    }
}
