
CREATE TABLE ACADEMIC_YEAR
(
	ACADEM_YEAR          VARCHAR2(20) NULL ,
	ACADEM_YEAR_ID       INTEGER NOT NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_ACADEMIC_YEAR ON ACADEMIC_YEAR
(ACADEM_YEAR_ID   ASC);

ALTER TABLE ACADEMIC_YEAR
	ADD CONSTRAINT  XPK_ACADEMIC_YEAR PRIMARY KEY (ACADEM_YEAR_ID);

CREATE TABLE CLASS_ROOM
(
	CLASS_ID             INTEGER NOT NULL ,
	CLASS_NUMBER         INTEGER NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_CLASS_ROOM ON CLASS_ROOM
(CLASS_ID   ASC);

ALTER TABLE CLASS_ROOM
	ADD CONSTRAINT  XPK_CLASS_ROOM PRIMARY KEY (CLASS_ID);

CREATE TABLE DISCIPLINE
(
	DISCIPLINE_ID        INTEGER NOT NULL ,
	DISCIPLINE_NAME      VARCHAR2(20) NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_DISCIPLINE ON DISCIPLINE
(DISCIPLINE_ID   ASC);

ALTER TABLE DISCIPLINE
	ADD CONSTRAINT  XPK_DISCIPLINE PRIMARY KEY (DISCIPLINE_ID);

CREATE TABLE FACULTY
(
	FAC_ID               INTEGER NOT NULL ,
	FAC_NAME             VARCHAR2(20) NULL ,
	MEGAFAC_ID           INTEGER NOT NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_FAC ON FACULTY
(FAC_ID   ASC);

ALTER TABLE FACULTY
	ADD CONSTRAINT  XPK_FAC PRIMARY KEY (FAC_ID);

CREATE TABLE FACULTY_LECTURER
(
	LEC_ID               INTEGER NOT NULL ,
	FAC_ID               INTEGER NOT NULL ,
	FAC_LECT_ID          INTEGER NOT NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_FAC_LECTUR ON FACULTY_LECTURER
(FAC_LECT_ID   ASC);

ALTER TABLE FACULTY_LECTURER
	ADD CONSTRAINT  XPK_FAC_LECTUR PRIMARY KEY (FAC_LECT_ID);

CREATE TABLE GROUPS
(
	GROUP_ID             INTEGER NOT NULL ,
	SPEC_ID              INTEGER NULL ,
	GROUP_NUM            VARCHAR2(20) NULL ,
	COURSE               INTEGER NULL ,
	EDUCATION_TIME_FROM  DATE NULL ,
	EDUCATION_TIME_TO    DATE NULL ,
	ACADEM_YEAR_ID       INTEGER NOT NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_GROUP ON GROUPS
(GROUP_ID   ASC);

ALTER TABLE GROUPS
	ADD CONSTRAINT  XPK_GROUP PRIMARY KEY (GROUP_ID);

CREATE TABLE LECTURER
(
	LEC_ID               INTEGER NOT NULL ,
	POST                 VARCHAR2(20) NULL ,
	WORK_PERIOD_FROM     DATE NULL ,
	WORK_PERIOD_TO       DATE NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_LECTURER ON LECTURER
(LEC_ID   ASC);

ALTER TABLE LECTURER
	ADD CONSTRAINT  XPK_LECTURER PRIMARY KEY (LEC_ID);

CREATE TABLE MEGAFACULTY
(
	MEGAFAC_ID           INTEGER NOT NULL ,
	MFACULTY_NAME        VARCHAR2(20) NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_MFAC ON MEGAFACULTY
(MEGAFAC_ID   ASC);

ALTER TABLE MEGAFACULTY
	ADD CONSTRAINT  XPK_MFAC PRIMARY KEY (MEGAFAC_ID);

CREATE TABLE OCCUPATION
(
	OCCUPATION_ID        INTEGER NOT NULL ,
	OCCUPATON_NUM        INTEGER NULL ,
	OCCUPATION_TIME_FROM DATE NULL ,
	OCCUPATION_TIME_TO   DATE NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_OCCUPATION ON OCCUPATION
(OCCUPATION_ID   ASC);

ALTER TABLE OCCUPATION
	ADD CONSTRAINT  XPK_OCCUPATION PRIMARY KEY (OCCUPATION_ID);

CREATE TABLE ODEVITY_WEEK
(
	ODEVITY_ID           INTEGER NOT NULL ,
	WEEK                 VARCHAR2(20) NULL  CONSTRAINT  VR_WEEK CHECK (WEEK IN ('EVEN', 'UNEVER')),
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_ODEVITY_WEEK ON ODEVITY_WEEK
(ODEVITY_ID   ASC);

ALTER TABLE ODEVITY_WEEK
	ADD CONSTRAINT  XPK_ODEVITY_WEEK PRIMARY KEY (ODEVITY_ID);

CREATE TABLE PERSONS
(
	PERSON_ID            INTEGER NOT NULL ,
	SECOND_NAME          VARCHAR2(20) NULL ,
	FIRST_NAME           VARCHAR2(20) NULL ,
	PATRONYMIC_NAME      VARCHAR2(20) NULL ,
	BIRTH_DATE           DATE NULL ,
	BIRTH_PLACE          VARCHAR2(20) NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_PERSON ON PERSONS
(PERSON_ID   ASC);

ALTER TABLE PERSONS
	ADD CONSTRAINT  XPK_PERSON PRIMARY KEY (PERSON_ID);

CREATE TABLE PROGRAM_TRACK
(
	PROG_ID              INTEGER NOT NULL ,
	FAC_ID               INTEGER NULL ,
	PROGM_NAME           VARCHAR2(20) NULL ,
	PROGRAM_TRACK_NUM    VARCHAR2(20) NULL ,
	PROGM_TYPE           VARCHAR2(20) NULL  CONSTRAINT  VR_TYPE CHECK (PROGM_TYPE IN ('FULL_TIME', 'PART_TIME')),
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_PROGRAM_TRACK ON PROGRAM_TRACK
(PROG_ID   ASC);

ALTER TABLE PROGRAM_TRACK
	ADD CONSTRAINT  XPK_PROGRAM_TRACK PRIMARY KEY (PROG_ID);

CREATE TABLE RESULTS
(
	RESULT               VARCHAR2(20) NULL ,
	EX_TYPE              VARCHAR2(20) NULL  CONSTRAINT  VR_RESULT_TYPE CHECK (EX_TYPE IN ('EXAM', 'PASS_FAIL_EXAM')),
	DISCIPLINE_ID        INTEGER NOT NULL ,
	RESULT_DATE          DATE NULL ,
	RESULT_EU            VARCHAR2(20) NULL ,
	ACADEM_YEAR_ID       INTEGER NOT NULL ,
	RESULT_ID            INTEGER NOT NULL ,
	STUDENT_ID           INTEGER NOT NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_RESULTS ON RESULTS
(RESULT_ID   ASC);

ALTER TABLE RESULTS
	ADD CONSTRAINT  XPK_RESULTS PRIMARY KEY (RESULT_ID);

CREATE TABLE SPECIALITY
(
	SPEC_ID              INTEGER NOT NULL ,
	SPEC_NAME            VARCHAR2(20) NULL ,
	SPEC_NUMBER          VARCHAR2(20) NULL ,
	SPEC_DEGREE          VARCHAR2(10) NULL  CONSTRAINT  VR_DEGREE CHECK (SPEC_DEGREE IN ('MAGISTER', 'BACHELOR')),
	FREE_EDUC_COUNT      INTEGER NULL ,
	PAID_EDUC_COUNT      INTEGER NULL ,
	SPONSORED_EDUC_COUNT INTEGER NULL ,
	PROG_ID              INTEGER NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_PROGR_SPECIALITY ON SPECIALITY
(SPEC_ID   ASC);

ALTER TABLE SPECIALITY
	ADD CONSTRAINT  XPK_PROGR_SPECIALITY PRIMARY KEY (SPEC_ID);

CREATE TABLE STUDENT
(
	PERSON_ID            INTEGER NOT NULL ,
	EDUCATION_TYPE       VARCHAR2(20) NULL  CONSTRAINT  VR_EDUCATION_TYPE CHECK (EDUCATION_TYPE IN ('FREE', 'PAID', 'SPONSORED')),
	GROUP_ID             INTEGER NULL ,
	STUDENT_ID           INTEGER NOT NULL ,
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_STUDENT ON STUDENT
(STUDENT_ID   ASC);

ALTER TABLE STUDENT
	ADD CONSTRAINT  XPK_STUDENT PRIMARY KEY (STUDENT_ID);

CREATE TABLE TIME_TABLE
(
	WEEK_DAY_ID          INTEGER NOT NULL ,
	OCCUPATION_ID        INTEGER NOT NULL ,
	ODEVITY_ID           INTEGER NOT NULL ,
	VARIANT_OCCUPATION_ID INTEGER NOT NULL ,
	CLASS_ID             INTEGER NOT NULL ,
	GROUP_ID             INTEGER NOT NULL ,
	DISCIPLINE_ID        INTEGER NOT NULL 
);

CREATE UNIQUE INDEX XPK_TIME_TABLE ON TIME_TABLE
(OCCUPATION_ID   ASC,WEEK_DAY_ID   ASC,ODEVITY_ID   ASC,VARIANT_OCCUPATION_ID   ASC,CLASS_ID   ASC,GROUP_ID   ASC,DISCIPLINE_ID   ASC);

ALTER TABLE TIME_TABLE
	ADD CONSTRAINT  XPK_TIME_TABLE PRIMARY KEY (OCCUPATION_ID,WEEK_DAY_ID,ODEVITY_ID,VARIANT_OCCUPATION_ID,CLASS_ID,GROUP_ID,DISCIPLINE_ID);

CREATE TABLE VARIANT_OCCUPATION
(
	VARIANT_OCCUPATION_ID INTEGER NOT NULL ,
	VAR_OCC_TYPE         VARCHAR2(20) NULL  CONSTRAINT  VR_OCCUPATION_TYPE CHECK (VAR_OCC_TYPE IN ('LECTURE', 'PRACTIC')),
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_ARIANT_OCC ON VARIANT_OCCUPATION
(VARIANT_OCCUPATION_ID   ASC);

ALTER TABLE VARIANT_OCCUPATION
	ADD CONSTRAINT  XPK_ARIANT_OCC PRIMARY KEY (VARIANT_OCCUPATION_ID);

CREATE TABLE WEEK_DAY
(
	WEEK_DAY_ID          INTEGER NOT NULL ,
	DAY                  VARCHAR2(20) NULL  CONSTRAINT  VR_DAY CHECK (DAY IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY')),
	CREAT_TIME           DATE NULL ,
	UPDATE_TIME          DATE NULL 
);

CREATE UNIQUE INDEX XPK_WEEK_DAY ON WEEK_DAY
(WEEK_DAY_ID   ASC);

ALTER TABLE WEEK_DAY
	ADD CONSTRAINT  XPK_WEEK_DAY PRIMARY KEY (WEEK_DAY_ID);

ALTER TABLE FACULTY
	ADD (CONSTRAINT R_33 FOREIGN KEY (MEGAFAC_ID) REFERENCES MEGAFACULTY (MEGAFAC_ID));

ALTER TABLE FACULTY_LECTURER
	ADD (CONSTRAINT R_15 FOREIGN KEY (FAC_ID) REFERENCES FACULTY (FAC_ID));

ALTER TABLE FACULTY_LECTURER
	ADD (CONSTRAINT R_16 FOREIGN KEY (LEC_ID) REFERENCES LECTURER (LEC_ID));

ALTER TABLE GROUPS
	ADD (CONSTRAINT R_6 FOREIGN KEY (SPEC_ID) REFERENCES SPECIALITY (SPEC_ID));

ALTER TABLE GROUPS
	ADD (CONSTRAINT R_29 FOREIGN KEY (ACADEM_YEAR_ID) REFERENCES ACADEMIC_YEAR (ACADEM_YEAR_ID));

ALTER TABLE LECTURER
	ADD (CONSTRAINT R_7 FOREIGN KEY (LEC_ID) REFERENCES PERSONS (PERSON_ID));

ALTER TABLE PROGRAM_TRACK
	ADD (CONSTRAINT R_4 FOREIGN KEY (FAC_ID) REFERENCES FACULTY (FAC_ID));

ALTER TABLE RESULTS
	ADD (CONSTRAINT R_17 FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT (STUDENT_ID));

ALTER TABLE RESULTS
	ADD (CONSTRAINT R_18 FOREIGN KEY (DISCIPLINE_ID) REFERENCES DISCIPLINE (DISCIPLINE_ID));

ALTER TABLE RESULTS
	ADD (CONSTRAINT R_31 FOREIGN KEY (ACADEM_YEAR_ID) REFERENCES ACADEMIC_YEAR (ACADEM_YEAR_ID));

ALTER TABLE SPECIALITY
	ADD (CONSTRAINT R_26 FOREIGN KEY (PROG_ID) REFERENCES PROGRAM_TRACK (PROG_ID));

ALTER TABLE STUDENT
	ADD (CONSTRAINT R_8 FOREIGN KEY (PERSON_ID) REFERENCES PERSONS (PERSON_ID));

ALTER TABLE STUDENT
	ADD (CONSTRAINT R_28 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_19 FOREIGN KEY (WEEK_DAY_ID) REFERENCES WEEK_DAY (WEEK_DAY_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_20 FOREIGN KEY (ODEVITY_ID) REFERENCES ODEVITY_WEEK (ODEVITY_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_21 FOREIGN KEY (OCCUPATION_ID) REFERENCES OCCUPATION (OCCUPATION_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_22 FOREIGN KEY (VARIANT_OCCUPATION_ID) REFERENCES VARIANT_OCCUPATION (VARIANT_OCCUPATION_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_23 FOREIGN KEY (CLASS_ID) REFERENCES CLASS_ROOM (CLASS_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_24 FOREIGN KEY (GROUP_ID) REFERENCES GROUPS (GROUP_ID));

ALTER TABLE TIME_TABLE
	ADD (CONSTRAINT R_25 FOREIGN KEY (DISCIPLINE_ID) REFERENCES DISCIPLINE (DISCIPLINE_ID));